# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QGraphicsPixmapItem

import graph_model.graph as g


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 480)
        Dialog.setMinimumSize(QtCore.QSize(1000, 480))
        Dialog.setMaximumSize(QtCore.QSize(1280, 720))
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(-50, -8, 1361, 751))
        self.listView.setStyleSheet("    background-image: url(./UI/background.jpg);\n"
                                    "    background-position: center;\n"
                                    "    background-repeat: no-repeat;\n"
                                    "    background-attachment: fixed; \n"
                                    "    background-size: contain;")
        self.listView.setObjectName("listView")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 180, 75, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(12, 40, 171, 131))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setOverwriteMode(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(59, 13, 31, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(617, 42, 361, 281))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(620, 330, 351, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(220, 40, 381, 281))
        self.graphicsView.setObjectName("graphicsView")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(730, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 250, 191, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 280, 75, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(self.getgraph)
        self.pushButton.clicked.connect(self.runGA)

    def getgraph(self):
        self.graph_model = g.Graph_Model(self.plainTextEdit)
        self.graph_model.generateImg('input')
        pixmap = QPixmap(r'./process record/input.png')
        pixmap_item = QGraphicsPixmapItem(pixmap)
        # 创建场景和将图像项添加到场景
        scene = QtWidgets.QGraphicsScene()
        scene.addItem(pixmap_item)

        # 将场景设置到 graphicsView
        self.graphicsView.setScene(scene)

        # 如果需要，你可以调整视图大小以适应场景内容
        self.graphicsView.fitInView(scene.sceneRect(), QtCore.Qt.KeepAspectRatio)

    def runGA(self):
        current_text = self.comboBox_2.currentText()
        print(current_text)
        self.graph_model.RunGraphAlgorithm(current_text)
        self.graph_model.generateImg('output')
        pixmap = QPixmap(r'./process record/output.png')
        pixmap_item = QGraphicsPixmapItem(pixmap)
        # 创建场景和将图像项添加到场景
        scene = QtWidgets.QGraphicsScene()
        scene.addItem(pixmap_item)

        # 将场景设置到 graphicsView
        self.graphicsView_2.setScene(scene)

        # 如果需要，你可以调整视图大小以适应场景内容
        self.graphicsView_2.fitInView(scene.sceneRect(), QtCore.Qt.KeepAspectRatio)
        #
        if self.graph_model.output_Path is not None:
            self.textBrowser.setText("path矩阵：\n" + str(self.graph_model.output_Path))
            self.textBrowser.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog", "显示图"))
        self.plainTextEdit.setPlaceholderText(_translate("Dialog", "请以邻接矩阵形式输入图"))
        self.label.setText(_translate("Dialog", "输入"))
        self.label_3.setText(_translate("Dialog", "结果可视化"))
        self.label_2.setText(_translate("Dialog", "图的可视化"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "最小生成树Kruskal"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "最小生成树Prime"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "最小生成树破圈法"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "最短路径Dijkstra"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "最短路径Floyd"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "最短路径Floyd-Warshall"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "最大匹配匈牙利"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "最优匹配Kuhn-Munkres"))
        self.pushButton.setText(_translate("Dialog", "确认"))
